name: CI

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  pest:
    name: Tests (Pest) L${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [8, 9]

    steps:
    - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

    - uses: actions/checkout@v2
    - name: Install composer dependencies
      run: composer require "laravel/framework:^${{ matrix.laravel }}.0"
    - name: Run tests
      run: vendor/bin/pest
