name: CI

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  pest:
    name: Tests (Pest) L${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [7, 8, 9]
        include:
          -   laravel: 7
              testbench: 6.7
          -   laravel: 8
              testbench: 6.7
          -   laravel: 9
              testbench: 7.0

    steps:
    - uses: actions/checkout@v2
    - name: Install composer dependencies
      run: composer require "laravel/framework:^${{ matrix.laravel }}.0" "orchestra/testbench:^${{ matrix.testbench }} --dev"
    - name: Run tests
      run: vendor/bin/pest
